reset_reminder:
  name: Erinnerung zurücksetzen
  description: Setzt den Countdown einer Erinnerung zurück auf das ursprüngliche Intervall
  fields:
    entity_id:
      name: Entität ID
      description: Die Entität ID des Countdown-Sensors
      required: true
      selector:
        entity:
          domain: sensor
          integration: recurring_reminders

set_reminder_days:
  name: Erinnerungs-Tage setzen
  description: Setzt den Countdown auf einen benutzerdefinierten Wert
  fields:
    entity_id:
      name: Entität ID
      description: Die Entität ID des Countdown-Sensors
      required: true
      selector:
        entity:
          domain: sensor
          integration: recurring_reminders
    days:
      name: Anzahl Tage
      description: Anzahl der Tage bis zur nächsten Erinnerung
      required: true
      selector:
        number:
          min: 0
          max: 365
          mode: box