reset_reminder:
  name: Erinnerung zurücksetzen
  description: Setzt den Countdown einer Erinnerung zurück auf das ursprüngliche Intervall
  fields:
    entity_id:
      name: Entität ID
      description: Die Entität ID des Countdown- oder Intervall-Sensors
      required: true
      selector:
        entity:
          domain: sensor
          integration: recurring_reminders

set_reminder_days:
  name: Erinnerungs-Tage setzen
  description: Setzt den Countdown auf einen benutzerdefinierten Wert
  fields:
    entity_id:
      name: Entität ID
      description: Die Entität ID des Countdown- oder Intervall-Sensors
      required: true
      selector:
        entity:
          domain: sensor
          integration: recurring_reminders
    days:
      name: Anzahl Tage
      description: Anzahl der Tage bis zur nächsten Erinnerung
      required: true
      selector:
        number:
          min: 0
          max: 365
          mode: box

set_reminder_interval:
  name: Erinnerungs-Intervall ändern
  description: Ändert das Intervall einer Erinnerung (z.B. von 7 auf 14 Tage)
  fields:
    entity_id:
      name: Entität ID
      description: Die Entität ID des Intervall-Sensors (endet mit '_intervall')
      required: true
      selector:
        entity:
          domain: sensor
          integration: recurring_reminders
    interval:
      name: Neues Intervall
      description: Neues Intervall in Tagen (z.B. 14 für alle 14 Tage)
      required: true
      selector:
        number:
          min: 1
          max: 365
          mode: box